### ISSUE TITLE
Require authentication before viewing

### ISSUE THREAD

**Issue by Nimphal** [ministryofjustice/operations-engineering-reports#52] opened 2022-06-29 12:59 UTC
Using Auth0, probably using GSuite as the source of truth so we don't require a GH account. GH can also work if not possible otherwise.

Unauthenticated users can still view the current public view.

**Comment by AntonyBishop** [comment] 2022-07-04 09:28
Duplicate of https://github.com/ministryofjustice/operations-engineering/issues/1124

**Closed by AntonyBishop** 2022-07-04 09:28 UTC
